### PR TITLE
Getting started corrections

### PR DESCRIPTION
**Pull request by rickbeerendonk**
Result of rebuilding the tutorial app: https://github.com/rickbeerendonk/ReactJS.NET-getting-started-tutorial/tree/1.3

### CODE REVIEW

**Comment by Daniel15** [comment]
Thanks for doing that Rick! I've been meaning to do another run-through of the tutorial myself.

**Comment by rickbeerendonk** [comment]
@Daniel15 Only adding bundling is a bit tough, because the BundleConfig.cs and its registration in Global.asax is not part of an Empty MVC project. The tutorial assumes it is though. You can see here what was needed to make it work: https://github.com/rickbeerendonk/ReactJS.NET-getting-started-tutorial/commit/540fd669dda4e6428481085495c5337c262c64ca

**Comment by Daniel15** [comment]
The "ReactJS.NET - JSX for ASP.NET Web Optimization Framework" package should install ASP.NET Bundling and Minification, which should also create the BundleConfig.cs. Does it not do that?

I'm considering splitting that out into a separate page of the tutorial as soon I'm going to write some documentation about using Webpack instead.

**Comment by rickbeerendonk** [comment]
I just tested it again in both a new MVC 4 and a new MVC 5 project, as well as in my tutorial code (MVC 4) and the BundleConfig.cs is not created. It creates a ReactConfig.cs, did you mean that one?

**Pull request merged**
