### PR TITLE
Added a ability to select the default JavaScript engine

### PR DESCRIPTION
**Pull request by Taritsyn**
This is not a classic pull request, but rather a proposal to improve the React.NET. This improvement will allow to meet the expectations of following users: [dima117](https://github.com/reactjs/React.NET/issues/360#issuecomment-291054084), [dgpedro](https://github.com/reactjs/React.NET/issues/190#issuecomment-259102850), [luty81](https://github.com/reactjs/React.NET/issues/338#issuecomment-268811536), [malachib](https://github.com/reactjs/React.NET/issues/355#issue-192121039), [ORuban](https://github.com/reactjs/React.NET/issues/379#issue-210133864), [jyee117](https://github.com/reactjs/React.NET/issues/400#issuecomment-297812855) and [mattgross76](https://github.com/reactjs/React.NET/issues/410#issuecomment-302524022).

### CODE REVIEW

**Comment by Daniel15** [comment]
This seems reasonable. Could you please add a unit test for this too?

**Comment by Taritsyn** [comment]
Added a unit tests.

**Comment by Daniel15** [comment]
Thank you!

**Comment by Daniel15** [comment]
This is included in the 3.1 release: https://reactjs.net/2017/07/3.1.0-release.html. Thanks for your contribution, Andrey!

**Pull request merged**
