### PR TITLE
Update Copyrights to Present

### PR DESCRIPTION
**Pull request by lazytype**
Might be better to be more future-proof by saying "2014-Present" instead.

### CODE REVIEW

**Comment by Daniel15** [comment]
I like the idea of "2014-Present", would you be able to update this PR to use that instead? :smile:

**Comment by lazytype** [comment]
Sure

**Comment by lazytype** [comment]
Updated :)

**Comment by Daniel15** [comment]
Manually merged in df0313d652b339b1f6cdbf59811da219611c0973 due to a conflict in one file. Thanks for your contribution, and sorry it took me so long to reply!

**Pull request merged**
