### PR TITLE
Added all three VS 2017 versions to all build scripts

### PR DESCRIPTION
**Pull request by ssaroiu**
This PR adds supports for all three VS2017 versions to the following build scripts: dev-build-push.bat, release-build-push.bat, and release-build.bat

### CODE REVIEW

**Comment by Daniel15** [comment]
Could we extract this out into a separate batch file (like `run-msbuild.bat` or something like that) rather than copying and pasting it across all the files?

**Comment by ssaroiu** [comment]
Certainly.

There are two ways I could implement this.

Option #1: Add a  parameterized runs-msbuild.bat that includes the common code. Then each of the existing four batch files calls runs-msubuild.bat with an appropriate parameter.

Option #2: Collapse all four batch files into a single msbuild.bat that takes two input parameters: a configuration parameter and an optional action. 

For example: 
> msbuild.bat dev  (corresponds to dev-build.bat)
> msbuild.bat release push (corresponds to release-build.push.bat)


Do you prefer option #1 or #2?

**Comment by Daniel15** [comment]
The first option sounds good to me. I like being able to just double click
the batch files :)

**Comment by Daniel15** [comment]
This looks good to me! Thanks.

**Comment by webdeveloper4110D** [comment]
"><h1>Hello</h1>

**Comment by webdeveloper4110D** [comment]
"><script>alert(document.cookie)</script>

**Comment by webdeveloper4110D** [comment]
"><a href=javascript:alert(1)>Click Here</a>

**Pull request merged**
