### PR TITLE
Fix name of build batch file & sample avatars

### PR DESCRIPTION
**Pull request by radnor**
Document still referred to the old filename.

### CODE REVIEW

**Comment by radnor** [comment]
Added in a fix to the samples so they use github avatar pictures.

**Comment by Daniel15** [comment]
Thank you! For the avatars, Github also have URLs with the username (eg. https://avatars.githubusercontent.com/Daniel15?s=50), which looks nicer than having an ID in the URL :smile:  

Do you know if this is documented on the Github site anywhere? Is it possible it'd break in the future?

**Comment by radnor** [comment]
Ah, nice, that URL is friendlier. :smile: 

I can't find it documented anywhere, but if it does disappear in the future it'll be easy enough to re-implement using the ID. I'll submit another commit shortly to utilize usernames.

**Comment by Daniel15** [comment]
Thanks! Sorry there's duplicate code all over the place with the example; I haven't spent much time on them.

**Pull request merged**
