### PR TITLE
ASP.NET 5 (originally vNext) support

### PR DESCRIPTION
**Pull request by Daniel15**
Add support for ASP.NET 5 (formerly known as vNext)

 - [x] Integrate with its IoC container
 - [x] Create middleware for transforming JSX files (or see if OWIN middleware can be reused)
 - [x] Add to build script
     - [x] Get versioning of assembly working
     - [x] Produce NuGet package
 - [ ] Write documentation
 - [x] ???
 - [ ] Profit!

### CODE REVIEW

**Comment by Daniel15** [comment]
Version number can be set through `K_BUILD_VERSION` environment variable: https://github.com/aspnet/XRE/issues/1284

**Comment by gabrielsadaka** [comment]
This is awesome, I've been planning to start learning react and ASP.net vnext now I can do both!

**Comment by Daniel15** [comment]
Boom, time to party :smile:

**Comment by luisrudge** [comment]
Awesome work guys!

**Comment by luisrudge** [comment]
Does it run on coreclr?

**Comment by ctolkien** [comment]
:astonished:

**Comment by Daniel15** [comment]
@luisrudge No CoreCLR support yet, that depends on the dependencies first (JavaScriptEngineSwitcher, ClearScript, and optionally MsieJavaScriptEngine)

**Comment by luisrudge** [comment]
Ok, that's great! Thanks!

**Comment by Daniel15** [comment]
Basic getting started guide here: http://reactjs.net/getting-started/aspnet5.html

**Comment by luisrudge** [comment]
Awesome! THanks!

**Comment by jimitndiaye** [comment]
@Daniel15 [this thread](https://clearscript.codeplex.com/discussions/648351) on the clear script forums discusses the problems facing support for CoreClr but suggests potential cross-platform alternatives: [Vroom](https://github.com/fogzot/vroomjs) and [V8.net](https://v8dotnet.codeplex.com/). Would they be suitable alternatives?

**Comment by Daniel15** [comment]
@jimitndiaye I'm actually using VroomJs for Linux and Mac OS support, but I never managed to get the required version of V8 (3.17.16.2) to compile properly on Windows. I don't have the expertise to upgrade VroomJs to support newer versions of V8, as I have very little C and C++ experience.

**Pull request merged**
