### PR TITLE
Update tutorial.md

### PR DESCRIPTION
**Pull request by danpadmore**
Correct the highlighted line to match the change that is being discussed, namely that the CommentForm can call the callback when the user submits the form

### CODE REVIEW

**Comment by Daniel15** [comment]
Could you please see if the ASP.NET 4 tutorial needs to be updated too? I
don't have my computer with me right now so it's difficult for me to check
:)

**Comment by danpadmore** [comment]
You're right, [the ASP.NET 4 tutorial](https://reactjs.net/getting-started/tutorial_aspnet4.html) needs to be updated in the same way.

I'll attempt to include it in this pull request.

**Comment by Daniel15** [comment]
You can include the change in the pull request if you switch to the right
branch on Github and then edit the file on Github :)

**Comment by danpadmore** [comment]
There it is :)

I didn't expect to do more than 1 change, so I had some more changes on a separate branch in my fork.
I merged them also into the branch for this pull request.
All of the changes are related to highlighting code lines in the tutorials (core/aspnet4)

**Comment by Daniel15** [comment]
Thanks!

**Pull request merged**
