### PR TITLE
upgraded packages in React.Core to fix security vulnerabilities

### PR DESCRIPTION
**Pull request by saranshkataria**

### CODE REVIEW

**Comment by dustinsoftware** [comment]
Looks like these package bumps came from `npm audit fix`. Thanks!

**Comment by saranshkataria** [comment]
@dustinsoftware yes, saw a security warning and updated those. gulp is one which I still haven't updated since it involved a breaking change and I was not sure what all would break because of it.

**Comment by Daniel15** [comment]
Thanks for the pull request! I guess we should upgrade to Babel 7 at some point...

**Comment by saranshkataria** [comment]
[babel-upgrade](https://github.com/babel/babel-upgrade) should be helpful in that I think?

**Pull request merged**
