### PR TITLE
Resolves Issue #521 Draft

### PR DESCRIPTION
**Pull request by suhailnaw**
Hi, I wanted to submit my first open source PR for issue #521 for some review!

> Add ClientOnly as a property to ReactComponent. When ReactEnvironment.CreateComponent is called, ClientOnly needs to be set.

I believe I set this correctly in ReactEnvironment.cs on lines 305 and 307.  Since this is a new parameter for ReactComponent, do I need to go in and add the ClientOnly parameter to every call of ReactComponent?  Or should I set a default value?

> When RenderJavaScript is called in ReactComponent, ClientOnly should be checked. If true, ReactDOM.render should be written to the script instead of ReactDOM.hydrate.

I used a ternary operator for the conditional in ReactComponent.cs on line 236.  I saw ternary operators used in other parts of the codebase, is it appropriate to use here?  Also, am I correctly referencing the ClientOnly property from the ReactComponent?

> Let's make sure to add a unit test for this as well.

I added two unit tests, one for each case.

### CODE REVIEW

**Comment by dustinsoftware** [comment]
Thanks for the PR. Please check the build failures by clicking the red X on the latest commit. Once the build passes let me know and I’ll give it some review :)

**Comment by dustinsoftware** [comment]
Hi there @suhailnaw, do you have time to continue with this PR? If not I'll finish it up and merge it in.

**Comment by suhailnaw** [comment]
Hey @dustinsoftware, I'm meeting with my C# developer friend tomorrow evening to troubleshoot this issue and hope to have a working PR by the following day.  I hope I can still contribute on this bug!

**Comment by dustinsoftware** [comment]
Looks good at a first glance. Need to pull down and test locally before merging.

**Comment by dustinsoftware** [comment]
I had to bump React to a version higher than 16.0 to get the bug to repro. Thanks for the PR!

**Comment by Daniel15** [comment]
Thanks @suhailnaw for submitting this pull request, and thanks @dustinsoftware for reviewing and merging it!

**Comment by suhailnaw** [comment]
Thank you for all your support @dustinsoftware!  Feels good to have an open source contribution under my belt :)

**Comment by dustinsoftware** [comment]
@suhailnaw this has shipped, here are the release notes https://reactjs.net/2018/06/3.4.0-release.html

**Comment by suhailnaw** [comment]
Awesome, thanks for the shoutout on the release notes @dustinsoftware, I really appreciate it!!

**Comment by Daniel15** [comment]
I wrote the release notes :smile:  Thanks for your pull request!

**Comment by suhailnaw** [comment]
Thanks @Daniel15!! :)

**Pull request merged**
