### PR TITLE
Updating .NET Core libraries from 1.0 RC2 to 1.0 RTM

### PR DESCRIPTION
**Pull request by ShikiGami**
Changes from RC2 to RTM are minimal, so there shouldn't be that many problems

### CODE REVIEW

**Comment by Daniel15** [comment]
Nice, thanks! I'll wait and see if the AppVeyor build succeeds. AppVeyor may need to update something at their end, but I just want to see if the CI build succeeds before merging :)

**Comment by Daniel15** [comment]
Success! :smile:

**Comment by westdavidr** [comment]
So awesome! When will we see a new Nuget package release?

**Comment by Daniel15** [comment]
You can install version  `React.AspNet 2.4.1-dev-20160628-1635` or above from [the development/build server](http://reactjs.net/getting-started/download.html#development-builds) to install the new build. I'll do a proper release soon :)

**Comment by westdavidr** [comment]
That's amazing. Thank you so much.

**Comment by Daniel15** [comment]
Pushed this as version 2.5, will update documentation later today.

**Pull request merged**
