### PR TITLE
Minor adjustments to Tutorial for clarity

### PR DESCRIPTION
**Pull request by awayken**

### CODE REVIEW

**Comment by awayken** [comment]
I opened this pull request as I was working through the tutorial. I see that the tutorial has had changes me to it since then. Should I just close this pull request as being outdated?

**Comment by dustinsoftware** [comment]
Hey @awayken sorry, this fell off my radar. Yeah, please re-open it.

**Comment by dustinsoftware** [comment]
I see a number of grammar related changes that don't seem like an improvement, could you share why some of the previous wording was confusing?

**Comment by awayken** [comment]
@dustinsoftware I think I was reading through it with my Editor hat on. I just noticed some places where there were ambiguous pronouns, passive voice usage or where I felt the flow of the sentence could be improved. The updates were maybe more a matter of personal taste rather than strict grammatical rule violation.

**Comment by awayken** [comment]
I'm going to close this for now. When I opened the Issue, I was preparing for a presentation and going through the tutorial pretty closely. Now that I'm passed that, I'm not sure when I'll get back to reading the tutorial and offering suggestions.

**Comment by dustinsoftware** [comment]
Ok :)

**Pull request closed without merging**
