### PR TITLE
Upgrade to Visual Studio 2017 + csproj tooling

### PR DESCRIPTION
**Pull request by Daniel15**
Upgrades ReactJS.NET to use Visual Studio 2017 and the newer csproj tooling.

There's some issues that need to be fixed:

 - Dependencies in the NuGet package have the incorrect version (`1.0`)
 - React.MSBuild NuGet package is placing `.ps1` files in the wrong place (https://github.com/NuGet/Home/issues/5176)
 - A whole heap of build warnings:
```
"C:\src\React.NET\build.proj" (default target) (1) ->
"C:\src\React.NET\src\React.sln" (Rebuild target) (2) ->
"C:\src\React.NET\src\React.Sample.Mvc6\React.Sample.Mvc6.csproj.metaproj" (Rebuild target) (15) ->
"C:\src\React.NET\src\React.Sample.Mvc6\React.Sample.Mvc6.csproj" (Rebuild target) (18) ->
"C:\src\React.NET\src\React.Sample.Mvc6\React.Sample.Mvc6.csproj" (Rebuild target) (18:3) ->
(CoreCompile target) ->
  CSC : warning CS1701: Assuming assembly reference 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50 a3a' used by 'Microsoft.Extensions.DependencyInjection.Abstractions' matches identity 'System.Runtime, Version=4.1.0.0, Culture=neu tral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.Runtime', you may need to supply runtime policy [C:\src\React.NET\src\React.Sampl e.Mvc6\React.Sample.Mvc6.csproj]
  CSC : warning CS1701: Assuming assembly reference 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50 a3a' used by 'Microsoft.Extensions.Logging.Abstractions' matches identity 'System.Runtime, Version=4.1.0.0, Culture=neutral, Public KeyToken=b03f5f7f11d50a3a' of 'System.Runtime', you may need to supply runtime policy [C:\src\React.NET\src\React.Sample.Mvc6\React .Sample.Mvc6.csproj]
  CSC : warning CS1701: Assuming assembly reference 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50 a3a' used by 'Microsoft.Extensions.Configuration' matches identity 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToke n=b03f5f7f11d50a3a' of 'System.Runtime', you may need to supply runtime policy [C:\src\React.NET\src\React.Sample.Mvc6\React.Sample .Mvc6.csproj]
  Startup.cs(27,22): warning CS1701: Assuming assembly reference 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken= b03f5f7f11d50a3a' used by 'Microsoft.Extensions.Configuration' matches identity 'System.Runtime, Version=4.1.0.0, Culture=neutral,
PublicKeyToken=b03f5f7f11d50a3a' of 'System.Runtime', you may need to supply runtime policy [C:\src\React.NET\src\React.Sample.Mvc6 \React.Sample.Mvc6.csproj]
  CSC : warning CS1701: Assuming assembly reference 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50 a3a' used by 'System.Collections' matches identity 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a 3a' of 'System.Runtime', you may need to supply runtime policy [C:\src\React.NET\src\React.Sample.Mvc6\React.Sample.Mvc6.csproj]
  Controllers\HomeController.cs(60,5): warning CS1701: Assuming assembly reference 'System.Runtime, Version=4.0.0.0, Culture=neutra l, PublicKeyToken=b03f5f7f11d50a3a' used by 'System.Collections' matches identity 'System.Runtime, Version=4.1.0.0, Culture=neutral , PublicKeyToken=b03f5f7f11d50a3a' of 'System.Runtime', you may need to supply runtime policy [C:\src\React.NET\src\React.Sample.Mv c6\React.Sample.Mvc6.csproj]
  Controllers\HomeController.cs(61,5): warning CS1701: Assuming assembly reference 'System.Runtime, Version=4.0.0.0, Culture=neutra l, PublicKeyToken=b03f5f7f11d50a3a' used by 'System.Collections' matches identity 'System.Runtime, Version=4.1.0.0, Culture=neutral , PublicKeyToken=b03f5f7f11d50a3a' of 'System.Runtime', you may need to supply runtime policy [C:\src\React.NET\src\React.Sample.Mv c6\React.Sample.Mvc6.csproj]
  Controllers\HomeController.cs(62,5): warning CS1701: Assuming assembly reference 'System.Runtime, Version=4.0.0.0, Culture=neutra l, PublicKeyToken=b03f5f7f11d50a3a' used by 'System.Collections' matches identity 'System.Runtime, Version=4.1.0.0, Culture=neutral , PublicKeyToken=b03f5f7f11d50a3a' of 'System.Runtime', you may need to supply runtime policy [C:\src\React.NET\src\React.Sample.Mv c6\React.Sample.Mvc6.csproj]
  Controllers\HomeController.cs(63,5): warning CS1701: Assuming assembly reference 'System.Runtime, Version=4.0.0.0, Culture=neutra l, PublicKeyToken=b03f5f7f11d50a3a' used by 'System.Collections' matches identity 'System.Runtime, Version=4.1.0.0, Culture=neutral , PublicKeyToken=b03f5f7f11d50a3a' of 'System.Runtime', you may need to supply runtime policy [C:\src\React.NET\src\React.Sample.Mv c6\React.Sample.Mvc6.csproj]
  Controllers\HomeController.cs(64,5): warning CS1701: Assuming assembly reference 'System.Runtime, Version=4.0.0.0, Culture=neutra l, PublicKeyToken=b03f5f7f11d50a3a' used by 'System.Collections' matches identity 'System.Runtime, Version=4.1.0.0, Culture=neutral , PublicKeyToken=b03f5f7f11d50a3a' of 'System.Runtime', you may need to supply runtime policy [C:\src\React.NET\src\React.Sample.Mv c6\React.Sample.Mvc6.csproj]
  Controllers\HomeController.cs(58,19): warning CS1701: Assuming assembly reference 'System.Runtime, Version=4.0.0.0, Culture=neutr al, PublicKeyToken=b03f5f7f11d50a3a' used by 'System.Collections' matches identity 'System.Runtime, Version=4.1.0.0, Culture=neutra l, PublicKeyToken=b03f5f7f11d50a3a' of 'System.Runtime', you may need to supply runtime policy [C:\src\React.NET\src\React.Sample.M vc6\React.Sample.Mvc6.csproj]
  Controllers\HomeController.cs(68,5): warning CS1701: Assuming assembly reference 'System.Runtime, Version=4.0.0.0, Culture=neutra l, PublicKeyToken=b03f5f7f11d50a3a' used by 'System.Collections' matches identity 'System.Runtime, Version=4.1.0.0, Culture=neutral , PublicKeyToken=b03f5f7f11d50a3a' of 'System.Runtime', you may need to supply runtime policy [C:\src\React.NET\src\React.Sample.Mv c6\React.Sample.Mvc6.csproj]
  Controllers\HomeController.cs(69,5): warning CS1701: Assuming assembly reference 'System.Runtime, Version=4.0.0.0, Culture=neutra l, PublicKeyToken=b03f5f7f11d50a3a' used by 'System.Collections' matches identity 'System.Runtime, Version=4.1.0.0, Culture=neutral , PublicKeyToken=b03f5f7f11d50a3a' of 'System.Runtime', you may need to supply runtime policy [C:\src\React.NET\src\React.Sample.Mv c6\React.Sample.Mvc6.csproj]
  Controllers\HomeController.cs(70,5): warning CS1701: Assuming assembly reference 'System.Runtime, Version=4.0.0.0, Culture=neutra l, PublicKeyToken=b03f5f7f11d50a3a' used by 'System.Collections' matches identity 'System.Runtime, Version=4.1.0.0, Culture=neutral , PublicKeyToken=b03f5f7f11d50a3a' of 'System.Runtime', you may need to supply runtime policy [C:\src\React.NET\src\React.Sample.Mv c6\React.Sample.Mvc6.csproj]
  Controllers\HomeController.cs(71,5): warning CS1701: Assuming assembly reference 'System.Runtime, Version=4.0.0.0, Culture=neutra l, PublicKeyToken=b03f5f7f11d50a3a' used by 'System.Collections' matches identity 'System.Runtime, Version=4.1.0.0, Culture=neutral , PublicKeyToken=b03f5f7f11d50a3a' of 'System.Runtime', you may need to supply runtime policy [C:\src\React.NET\src\React.Sample.Mv c6\React.Sample.Mvc6.csproj]
  Controllers\HomeController.cs(72,5): warning CS1701: Assuming assembly reference 'System.Runtime, Version=4.0.0.0, Culture=neutra l, PublicKeyToken=b03f5f7f11d50a3a' used by 'System.Collections' matches identity 'System.Runtime, Version=4.1.0.0, Culture=neutral , PublicKeyToken=b03f5f7f11d50a3a' of 'System.Runtime', you may need to supply runtime policy [C:\src\React.NET\src\React.Sample.Mv c6\React.Sample.Mvc6.csproj]
  Controllers\HomeController.cs(73,5): warning CS1701: Assuming assembly reference 'System.Runtime, Version=4.0.0.0, Culture=neutra l, PublicKeyToken=b03f5f7f11d50a3a' used by 'System.Collections' matches identity 'System.Runtime, Version=4.1.0.0, Culture=neutral , PublicKeyToken=b03f5f7f11d50a3a' of 'System.Runtime', you may need to supply runtime policy [C:\src\React.NET\src\React.Sample.Mv c6\React.Sample.Mvc6.csproj]
  Controllers\HomeController.cs(74,5): warning CS1701: Assuming assembly reference 'System.Runtime, Version=4.0.0.0, Culture=neutra l, PublicKeyToken=b03f5f7f11d50a3a' used by 'System.Collections' matches identity 'System.Runtime, Version=4.1.0.0, Culture=neutral , PublicKeyToken=b03f5f7f11d50a3a' of 'System.Runtime', you may need to supply runtime policy [C:\src\React.NET\src\React.Sample.Mv c6\React.Sample.Mvc6.csproj]
  Controllers\HomeController.cs(66,20): warning CS1701: Assuming assembly reference 'System.Runtime, Version=4.0.0.0, Culture=neutr al, PublicKeyToken=b03f5f7f11d50a3a' used by 'System.Collections' matches identity 'System.Runtime, Version=4.1.0.0, Culture=neutra l, PublicKeyToken=b03f5f7f11d50a3a' of 'System.Runtime', you may need to supply runtime policy [C:\src\React.NET\src\React.Sample.M vc6\React.Sample.Mvc6.csproj]
  CSC : warning CS1701: Assuming assembly reference 'System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d5 0a3a' used by 'Microsoft.AspNetCore.Hosting' matches identity 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03 f5f7f11d50a3a' of 'System.Runtime', you may need to supply runtime policy [C:\src\React.NET\src\React.Sample.Mvc6\React.Sample.Mvc6 .csproj]
  Program.cs(23,19): warning CS1701: Assuming assembly reference 'System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken =b03f5f7f11d50a3a' used by 'Microsoft.AspNetCore.Hosting' matches identity 'System.Runtime, Version=4.1.0.0, Culture=neutral, Publi cKeyToken=b03f5f7f11d50a3a' of 'System.Runtime', you may need to supply runtime policy [C:\src\React.NET\src\React.Sample.Mvc6\Reac t.Sample.Mvc6.csproj]
  CSC : warning CS1701: Assuming assembly reference 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50 a3a' used by 'System.IO.FileSystem' matches identity 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d5 0a3a' of 'System.Runtime', you may need to supply runtime policy [C:\src\React.NET\src\React.Sample.Mvc6\React.Sample.Mvc6.csproj]
  Program.cs(25,21): warning CS1701: Assuming assembly reference 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken= b03f5f7f11d50a3a' used by 'System.IO.FileSystem' matches identity 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken =b03f5f7f11d50a3a' of 'System.Runtime', you may need to supply runtime policy [C:\src\React.NET\src\React.Sample.Mvc6\React.Sample. Mvc6.csproj]
  Program.cs(23,15): warning CS1701: Assuming assembly reference 'System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken =b03f5f7f11d50a3a' used by 'Microsoft.AspNetCore.Hosting.Abstractions' matches identity 'System.Runtime, Version=4.1.0.0, Culture=n eutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.Runtime', you may need to supply runtime policy [C:\src\React.NET\src\React.Sam ple.Mvc6\React.Sample.Mvc6.csproj]
  Program.cs(23,15): warning CS1701: Assuming assembly reference 'System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken =b03f5f7f11d50a3a' used by 'Microsoft.AspNetCore.Hosting.Abstractions' matches identity 'System.Runtime, Version=4.1.0.0, Culture=n eutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.Runtime', you may need to supply runtime policy [C:\src\React.NET\src\React.Sam ple.Mvc6\React.Sample.Mvc6.csproj]
  Program.cs(30,4): warning CS1701: Assuming assembly reference 'System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken= b03f5f7f11d50a3a' used by 'Microsoft.AspNetCore.Hosting.Abstractions' matches identity 'System.Runtime, Version=4.1.0.0, Culture=ne utral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.Runtime', you may need to supply runtime policy [C:\src\React.NET\src\React.Samp le.Mvc6\React.Sample.Mvc6.csproj]
  Startup.cs(38,4): warning CS1701: Assuming assembly reference 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b 03f5f7f11d50a3a' used by 'Microsoft.Extensions.DependencyInjection.Abstractions' matches identity 'System.Runtime, Version=4.1.0.0,  Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.Runtime', you may need to supply runtime policy [C:\src\React.NET\src \React.Sample.Mvc6\React.Sample.Mvc6.csproj]
  CSC : warning CS1701: Assuming assembly reference 'System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d5 0a3a' used by 'Microsoft.AspNetCore.Http' matches identity 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f 7f11d50a3a' of 'System.Runtime', you may need to supply runtime policy [C:\src\React.NET\src\React.Sample.Mvc6\React.Sample.Mvc6.cs proj]
  Startup.cs(40,4): warning CS1701: Assuming assembly reference 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b 03f5f7f11d50a3a' used by 'Microsoft.Extensions.DependencyInjection.Abstractions' matches identity 'System.Runtime, Version=4.1.0.0,  Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.Runtime', you may need to supply runtime policy [C:\src\React.NET\src \React.Sample.Mvc6\React.Sample.Mvc6.csproj]
  Startup.cs(43,4): warning CS1701: Assuming assembly reference 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b 03f5f7f11d50a3a' used by 'Microsoft.Extensions.DependencyInjection.Abstractions' matches identity 'System.Runtime, Version=4.1.0.0,  Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.Runtime', you may need to supply runtime policy [C:\src\React.NET\src \React.Sample.Mvc6\React.Sample.Mvc6.csproj]
  Controllers\HomeController.cs(82,16): warning CS1701: Assuming assembly reference 'System.Runtime, Version=4.0.0.0, Culture=neutr al, PublicKeyToken=b03f5f7f11d50a3a' used by 'System.Linq' matches identity 'System.Runtime, Version=4.1.0.0, Culture=neutral, Publ icKeyToken=b03f5f7f11d50a3a' of 'System.Runtime', you may need to supply runtime policy [C:\src\React.NET\src\React.Sample.Mvc6\Rea ct.Sample.Mvc6.csproj]
  Controllers\HomeController.cs(82,16): warning CS1701: Assuming assembly reference 'System.Runtime, Version=4.0.0.0, Culture=neutr al, PublicKeyToken=b03f5f7f11d50a3a' used by 'System.Linq.Parallel' matches identity 'System.Runtime, Version=4.1.0.0, Culture=neut ral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.Runtime', you may need to supply runtime policy [C:\src\React.NET\src\React.Sample .Mvc6\React.Sample.Mvc6.csproj]
  Controllers\HomeController.cs(82,16): warning CS1701: Assuming assembly reference 'System.Runtime, Version=4.0.0.0, Culture=neutr al, PublicKeyToken=b03f5f7f11d50a3a' used by 'System.Linq.Expressions' matches identity 'System.Runtime, Version=4.1.0.0, Culture=n eutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.Runtime', you may need to supply runtime policy [C:\src\React.NET\src\React.Sam ple.Mvc6\React.Sample.Mvc6.csproj]
  Controllers\HomeController.cs(89,19): warning CS1701: Assuming assembly reference 'System.Runtime, Version=4.0.0.0, Culture=neutr al, PublicKeyToken=b03f5f7f11d50a3a' used by 'System.Linq' matches identity 'System.Runtime, Version=4.1.0.0, Culture=neutral, Publ icKeyToken=b03f5f7f11d50a3a' of 'System.Runtime', you may need to supply runtime policy [C:\src\React.NET\src\React.Sample.Mvc6\Rea ct.Sample.Mvc6.csproj]
  Controllers\HomeController.cs(89,19): warning CS1701: Assuming assembly reference 'System.Runtime, Version=4.0.0.0, Culture=neutr al, PublicKeyToken=b03f5f7f11d50a3a' used by 'System.Linq.Parallel' matches identity 'System.Runtime, Version=4.1.0.0, Culture=neut ral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.Runtime', you may need to supply runtime policy [C:\src\React.NET\src\React.Sample .Mvc6\React.Sample.Mvc6.csproj]
  Controllers\HomeController.cs(89,19): warning CS1701: Assuming assembly reference 'System.Runtime, Version=4.0.0.0, Culture=neutr al, PublicKeyToken=b03f5f7f11d50a3a' used by 'System.Linq.Expressions' matches identity 'System.Runtime, Version=4.1.0.0, Culture=n eutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.Runtime', you may need to supply runtime policy [C:\src\React.NET\src\React.Sam ple.Mvc6\React.Sample.Mvc6.csproj]
  Controllers\HomeController.cs(89,19): warning CS1701: Assuming assembly reference 'System.Runtime, Version=4.0.0.0, Culture=neutr al, PublicKeyToken=b03f5f7f11d50a3a' used by 'System.Linq' matches identity 'System.Runtime, Version=4.1.0.0, Culture=neutral, Publ icKeyToken=b03f5f7f11d50a3a' of 'System.Runtime', you may need to supply runtime policy [C:\src\React.NET\src\React.Sample.Mvc6\Rea ct.Sample.Mvc6.csproj]
  Controllers\HomeController.cs(89,19): warning CS1701: Assuming assembly reference 'System.Runtime, Version=4.0.0.0, Culture=neutr al, PublicKeyToken=b03f5f7f11d50a3a' used by 'System.Linq.Parallel' matches identity 'System.Runtime, Version=4.1.0.0, Culture=neut ral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.Runtime', you may need to supply runtime policy [C:\src\React.NET\src\React.Sample .Mvc6\React.Sample.Mvc6.csproj]
  Controllers\HomeController.cs(89,19): warning CS1701: Assuming assembly reference 'System.Runtime, Version=4.0.0.0, Culture=neutr al, PublicKeyToken=b03f5f7f11d50a3a' used by 'System.Linq.Expressions' matches identity 'System.Runtime, Version=4.1.0.0, Culture=n eutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.Runtime', you may need to supply runtime policy [C:\src\React.NET\src\React.Sam ple.Mvc6\React.Sample.Mvc6.csproj]
  Startup.cs(50,4): warning CS1701: Assuming assembly reference 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b 03f5f7f11d50a3a' used by 'Microsoft.Extensions.Logging.Abstractions' matches identity 'System.Runtime, Version=4.1.0.0, Culture=neu tral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.Runtime', you may need to supply runtime policy [C:\src\React.NET\src\React.Sampl e.Mvc6\React.Sample.Mvc6.csproj]
  Startup.cs(53,8): warning CS1701: Assuming assembly reference 'System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken= b03f5f7f11d50a3a' used by 'Microsoft.AspNetCore.Hosting.Abstractions' matches identity 'System.Runtime, Version=4.1.0.0, Culture=ne utral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.Runtime', you may need to supply runtime policy [C:\src\React.NET\src\React.Samp le.Mvc6\React.Sample.Mvc6.csproj]
  Startup.cs(62,5): warning CS1701: Assuming assembly reference 'System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken= b03f5f7f11d50a3a' used by 'Microsoft.AspNetCore.Diagnostics' matches identity 'System.Runtime, Version=4.1.0.0, Culture=neutral, Pu blicKeyToken=b03f5f7f11d50a3a' of 'System.Runtime', you may need to supply runtime policy [C:\src\React.NET\src\React.Sample.Mvc6\R eact.Sample.Mvc6.csproj]
  Startup.cs(80,5): warning CS1701: Assuming assembly reference 'System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken= b03f5f7f11d50a3a' used by 'Microsoft.AspNetCore.Routing' matches identity 'System.Runtime, Version=4.1.0.0, Culture=neutral, Public KeyToken=b03f5f7f11d50a3a' of 'System.Runtime', you may need to supply runtime policy [C:\src\React.NET\src\React.Sample.Mvc6\React .Sample.Mvc6.csproj]
  Startup.cs(86,5): warning CS1701: Assuming assembly reference 'System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken= b03f5f7f11d50a3a' used by 'Microsoft.AspNetCore.Routing' matches identity 'System.Runtime, Version=4.1.0.0, Culture=neutral, Public KeyToken=b03f5f7f11d50a3a' of 'System.Runtime', you may need to supply runtime policy [C:\src\React.NET\src\React.Sample.Mvc6\React .Sample.Mvc6.csproj]


"C:\src\React.NET\build.proj" (default target) (1) ->
"C:\src\React.NET\src\React.sln" (Rebuild target) (2) ->
"C:\src\React.NET\src\React.Sample.ConsoleApp\React.Sample.ConsoleApp.csproj" (Rebuild target) (21) ->
"C:\src\React.NET\src\React.Sample.ConsoleApp\React.Sample.ConsoleApp.csproj" (Rebuild target) (21:3) ->
  CSC : warning CS1701: Assuming assembly reference 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50 a3a' used by 'System.Console' matches identity 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
of 'System.Runtime', you may need to supply runtime policy [C:\src\React.NET\src\React.Sample.ConsoleApp\React.Sample.ConsoleApp.cs proj]
  Program.cs(29,4): warning CS1701: Assuming assembly reference 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b 03f5f7f11d50a3a' used by 'System.Console' matches identity 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f 7f11d50a3a' of 'System.Runtime', you may need to supply runtime policy [C:\src\React.NET\src\React.Sample.ConsoleApp\React.Sample.C onsoleApp.csproj]
  Program.cs(30,4): warning CS1701: Assuming assembly reference 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b 03f5f7f11d50a3a' used by 'System.Console' matches identity 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f 7f11d50a3a' of 'System.Runtime', you may need to supply runtime policy [C:\src\React.NET\src\React.Sample.ConsoleApp\React.Sample.C onsoleApp.csproj]
  CSC : warning CS1701: Assuming assembly reference 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50 a3a' used by 'System.Collections' matches identity 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a 3a' of 'System.Runtime', you may need to supply runtime policy [C:\src\React.NET\src\React.Sample.ConsoleApp\React.Sample.ConsoleAp p.csproj]


"C:\src\React.NET\build.proj" (default target) (1) ->
(Package target) ->
  C:\Program Files\dotnet\sdk\1.0.0\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): warning : Issue found
with package 'React.MSBuild'. [C:\src\React.NET\src\React.MSBuild\React.MSBuild.csproj] [C:\src\React.NET\build.proj]
  C:\Program Files\dotnet\sdk\1.0.0\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): warning : Issue: Power Shell file outside tools folder. [C:\src\React.NET\src\React.MSBuild\React.MSBuild.csproj] [C:\src\React.NET\build.proj]
  C:\Program Files\dotnet\sdk\1.0.0\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): warning : Description:  The script file 'content\tools\install.ps1' is outside the 'tools' folder and hence will not be executed during installation of th is package. [C:\src\React.NET\src\React.MSBuild\React.MSBuild.csproj] [C:\src\React.NET\build.proj]
  C:\Program Files\dotnet\sdk\1.0.0\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): warning : Solution: Mo ve it into the 'tools' folder. [C:\src\React.NET\src\React.MSBuild\React.MSBuild.csproj] [C:\src\React.NET\build.proj]
  C:\Program Files\dotnet\sdk\1.0.0\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): warning : Issue: Power Shell file outside tools folder. [C:\src\React.NET\src\React.MSBuild\React.MSBuild.csproj] [C:\src\React.NET\build.proj]
  C:\Program Files\dotnet\sdk\1.0.0\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): warning : Description:  The script file 'contentFiles\any\net40\tools\install.ps1' is outside the 'tools' folder and hence will not be executed during ins tallation of this package. [C:\src\React.NET\src\React.MSBuild\React.MSBuild.csproj] [C:\src\React.NET\build.proj]
  C:\Program Files\dotnet\sdk\1.0.0\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): warning : Solution: Mo ve it into the 'tools' folder. [C:\src\React.NET\src\React.MSBuild\React.MSBuild.csproj] [C:\src\React.NET\build.proj]
  C:\Program Files\dotnet\sdk\1.0.0\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): warning : Issue: Power Shell file outside tools folder. [C:\src\React.NET\src\React.MSBuild\React.MSBuild.csproj] [C:\src\React.NET\build.proj]
  C:\Program Files\dotnet\sdk\1.0.0\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): warning : Description:  The script file 'content\tools\uninstall.ps1' is outside the 'tools' folder and hence will not be executed during installation of
this package. [C:\src\React.NET\src\React.MSBuild\React.MSBuild.csproj] [C:\src\React.NET\build.proj]
  C:\Program Files\dotnet\sdk\1.0.0\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): warning : Solution: Mo ve it into the 'tools' folder. [C:\src\React.NET\src\React.MSBuild\React.MSBuild.csproj] [C:\src\React.NET\build.proj]
  C:\Program Files\dotnet\sdk\1.0.0\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): warning : Issue: Power Shell file outside tools folder. [C:\src\React.NET\src\React.MSBuild\React.MSBuild.csproj] [C:\src\React.NET\build.proj]
  C:\Program Files\dotnet\sdk\1.0.0\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): warning : Description:  The script file 'contentFiles\any\net40\tools\uninstall.ps1' is outside the 'tools' folder and hence will not be executed during i nstallation of this package. [C:\src\React.NET\src\React.MSBuild\React.MSBuild.csproj] [C:\src\React.NET\build.proj]
  C:\Program Files\dotnet\sdk\1.0.0\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): warning : Solution: Mo ve it into the 'tools' folder. [C:\src\React.NET\src\React.MSBuild\React.MSBuild.csproj] [C:\src\React.NET\build.proj]
```

### CODE REVIEW

**Comment by Daniel15** [comment]
Version issue is tracked in https://github.com/NuGet/Home/issues/4337. Will need to work around it.

**Comment by Daniel15** [comment]
This builds on my computer and mostly seems to work, but is [broken on AppVeyor](https://ci.appveyor.com/project/Daniel15/react-net/build/211)

**Comment by defcon84** [comment]
Thanks! When will this be published to Nuget? :)

**Comment by Daniel15** [comment]
I didn't have any immediate plans to push these changes to NuGet, as the only real user-facing change is moving from .NET Core 1.0 to 1.1. I'll probably at least split the middleware out into a separate NuGet package (#388) before pushing.

**Comment by Daniel15** [comment]
@defcon84  - I'm going to publish this to NuGet tomorrow. You can use the dev server in the meantime.

**Comment by Daniel15** [comment]
This is included in the 3.1 release: https://reactjs.net/2017/07/3.1.0-release.html

**Pull request merged**
