### PR TITLE
Add NuGet package groupings to Renovate Bot config

### PR DESCRIPTION
**Pull request by rarkins**
Adds the following (separate) groupings:
- All packages from @Taritsyn's JavascriptEngineSwitcher repo
- All packages from https://github.com/aspnet/Extensions
- `Microsoft.AspNetCore*` packages plus those with source repo https://github.com/aspnet/MetaPackages or https://github.com/aspnet/AspNetCore
- `Microsoft.Owin*` packages

### CODE REVIEW

**Comment by rarkins** [comment]
Hi, I am the author of Renovate Bot but don't personally use .NET packages so I'm doing a little bit of guessing here. My goal is to combine packages that could or should be upgraded at the same time, so that you get less PRs.

You can see the results of these groupings in my fork: https://github.com/renovate-tests/React.NET/pulls

Please review these groupings and suggest if any more should be added or if any of the ones I propose are too aggressive.

**Comment by dustinsoftware** [comment]
Thanks! This is a great start, we can refine it as we go along :)

**Comment by rarkins** [comment]
Great, feel free to @ me from within an issue or PR if you'd like me to check or suggest anything

**Comment by Daniel15** [comment]
Thank you! This looks great to me 😄

**Pull request merged**
