### PR TITLE
Update to React 0.12.2

### LINKED ISSUE #63: Update to React 0.12.2

### PR DESCRIPTION
**Pull request by rickbeerendonk**
Fixes #63

### CODE REVIEW

**Comment by rickbeerendonk** [comment]
Oops, build failure.

**Comment by Daniel15** [comment]
I haven't looked at this diff yet as I'm away from my computer, but
JSXTransformer actually has some small patches applied to it to make it
work with the MSIE JavaScript engine (unfortunately I haven't documented
this yet). Basically all instances of string indexing (eg. `source[i]`) are
replaced with calls to charAt (`source.charAt(i)`). I've just been doing
this manually so far.

You can diff the old bundled JSXTransformer version with a vanilla version
off the Facebook CDN to see the differences.

**Comment by rickbeerendonk** [comment]
@Daniel15 Thank you, I will have a look.

**Comment by Daniel15** [comment]
Great, thanks! Looks like a fairly small update :)

**Pull request merged**
